baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Mario López'
theme = "cactus"

[params]
  showProjectsList = true
  projectsUrl = "https://github.com/marioolf"
  description = "Cybersecurity Researcher @ Gradiant. MSc in Cybersecurity. Computer Science Engineer. Here I post personal researchs, projects and walkthroughs from different certifications."
  colortheme = "dark"
  logo = "/images/logo.png"
  css = ["css/custom.css"]
  mainSectionTitle = "Recent Posts"
  ignoreLogs = ['warning-goldmark-raw-html']

[[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/mariolopezfeijoo/"

[[params.social]]    
    name = "email"
    link = "mariolfeijoo@gmail.com" # no need for "mailto:" at the start

[[params.social]]  
    name = "github"
    link = "https://github.com/marioolf"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4